CREATE TABLE users (
    username VARCHAR(24) NOT NULL PRIMARY KEY UNIQUE,
    password CHAR(128) NOT NULL,
    salt CHAR(128) NOT NULL 
) ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE tweetciks (
	id int(10) unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username varchar(24) NOT NULL,
	content varchar(140) NOT NULL,
	tweetcikdate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;